apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backuppc-remote.fullname" . }}-ssh-secrets
stringData:
  ssh_host_ed25519_key: {{ .Values.sshd.sshHostEd25519Key | quote }}
  ssh_host_ed25519_key.pub: {{ .Values.sshd.sshHostEd25519KeyPub | quote }}

