apiVersion: v1
kind: Service
metadata:
  name: {{ template "backuppc-remote.fullname" . }}
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
  selector:
    app.kubernetes.io/name: {{ include "backuppc-remote.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
